{{- if .Values.vulnProcessing.dedicated }}
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: mobius
    chart: mobius
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: mobius-vulnprocessing
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.vulnProcessing.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        metadata:
{{- with .Values.podAnnotations }}
          annotations:
{{- toYaml . | trim | nindent 12 }}
{{- end }}
          labels:
            app: mobius
            chart: mobius
            heritage: {{ .Release.Service }}
            release: {{ .Release.Name }}
        spec:
          restartPolicy: Never
          shareProcessNamespace: true
          containers:
          - name: mobius-vulnprocessing
            command: ["/bin/sh", "-c"]
            args:
              - |
                /usr/bin/mobius vuln_processing;
                {{- if .Values.gke.cloudSQL.enableProxy }}
                sql_proxy_pid=$(pgrep cloud_sql_proxy) && kill -INT $sql_proxy_pid;
                {{- end }}
            image: "{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
            resources:
              limits:
                cpu: {{ .Values.vulnProcessing.resources.limits.cpu }}
                memory: {{ .Values.vulnProcessing.resources.limits.memory }}
              requests:
                cpu: {{ .Values.vulnProcessing.resources.requests.cpu }}
                memory: {{ .Values.vulnProcessing.resources.requests.memory }}
            env:
              ## BEGIN MOBIUS SECTION
              - name: MOBIUS_VULNERABILITIES_DATABASES_PATH
                value: /tmp/vuln # /tmp might not work on all cloud providers by default
              # - name: MOBIUS_SERVER_ADDRESS
              #   value: "0.0.0.0:{{ .Values.mobius.listenPort }}"
              # - name: MOBIUS_AUTH_BCRYPT_COST
              #   value: "{{ .Values.mobius.auth.bcryptCost }}"
              # - name: MOBIUS_AUTH_SALT_KEY_SIZE
              #   value: "{{ .Values.mobius.auth.saltKeySize }}"
              # - name: MOBIUS_APP_TOKEN_KEY_SIZE
              #   value: "{{ .Values.mobius.app.tokenKeySize }}"
              # - name: MOBIUS_APP_TOKEN_VALIDITY_PERIOD
              #   value: "{{ .Values.mobius.app.inviteTokenValidityPeriod }}"
              # - name: MOBIUS_SESSION_KEY_SIZE
              #   value: "{{ .Values.mobius.session.keySize }}"
              # - name: MOBIUS_SESSION_DURATION
              #   value: "{{ .Values.mobius.session.duration }}"
              - name: MOBIUS_LOGGING_DEBUG
                value: "{{ .Values.mobius.logging.debug }}"
              - name: MOBIUS_LOGGING_JSON
                value: "{{ .Values.mobius.logging.json }}"
              - name: MOBIUS_LOGGING_DISABLE_BANNER
                value: "{{ .Values.mobius.logging.disableBanner }}"
              # - name: MOBIUS_SERVER_TLS
              #   value: "{{ .Values.mobius.tls.enabled }}"
              # {{- if .Values.mobius.tls.enabled }}
              # - name: MOBIUS_SERVER_TLS_COMPATIBILITY
              #   value: "{{ .Values.mobius.tls.compatibility }}"
              # - name: MOBIUS_SERVER_CERT
              #   value: "/secrets/tls/{{ .Values.mobius.tls.certSecretKey }}"
              # - name: MOBIUS_SERVER_KEY
              #   value: "/secrets/tls/{{ .Values.mobius.tls.keySecretKey }}"
              # {{- end }}
              {{- if .Values.mobius.license.secretName }}
              - name: MOBIUS_LICENSE_KEY
                valueFrom:
                  secretKeyRef:
                    key: {{ .Values.mobius.license.licenseKey }}
                    name: {{ .Values.mobius.license.secretName }}
              {{- end }}
              ## END MOBIUS SECTION
              ## BEGIN MYSQL SECTION
              - name: MOBIUS_MYSQL_ADDRESS
                value: "{{ .Values.database.address }}"
              - name: MOBIUS_MYSQL_DATABASE
                value: "{{ .Values.database.database }}"
              - name: MOBIUS_MYSQL_USERNAME
                value: "{{ .Values.database.username }}"
              - name: MOBIUS_MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.database.secretName }}
                    key: {{ .Values.database.passwordKey }}
              - name: MOBIUS_MYSQL_MAX_OPEN_CONNS
                value: "{{ .Values.database.maxOpenConns }}"
              - name: MOBIUS_MYSQL_MAX_IDLE_CONNS
                value: "{{ .Values.database.maxIdleConns }}"
              - name: MOBIUS_MYSQL_CONN_MAX_LIFETIME
                value: "{{ .Values.database.connMaxLifetime }}"
              {{- if .Values.database.tls.enabled }}
              {{- if .Values.database.tls.caCertKey }}
              - name: MOBIUS_MYSQL_TLS_CA
                value: "/secrets/mysql/{{ .Values.database.tls.caCertKey }}"
              {{- end }}
              {{- if .Values.database.tls.certKey }}
              - name: MOBIUS_MYSQL_TLS_CERT
                value: "/secrets/mysql/{{ .Values.database.tls.certKey }}"
              {{- end }}
              {{- if .Values.database.tls.keyKey }}
              - name: MOBIUS_MYSQL_TLS_KEY
                value: "/secrets/mysql/{{ .Values.database.tls.keyKey }}"
              {{- end }}
              - name: MOBIUS_MYSQL_TLS_CONFIG
                value: "{{ .Values.database.tls.config }}"
              - name: MOBIUS_MYSQL_TLS_SERVER_NAME
                value: "{{ .Values.database.tls.serverName }}"
              {{- end }}
              ## END MYSQL SECTION
              ## BEGIN MYSQL READ REPLICA SECTION
              {{- if .Values.database_read_replica }}
              {{- if .Values.database_read_replica.address }}
              - name: MOBIUS_MYSQL_READ_REPLICA_ADDRESS
                value: "{{ .Values.database_read_replica.address }}"
              {{- end }}
              {{- if .Values.database_read_replica.database }}
              - name: MOBIUS_MYSQL_READ_REPLICA_DATABASE
                value: "{{ .Values.database_read_replica.database }}"
              {{- end }}
              {{- if .Values.database_read_replica.username }}
              - name: MOBIUS_MYSQL_READ_REPLICA_USERNAME
                value: "{{ .Values.database_read_replica.username }}"
              {{- end }}
              {{- if .Values.database_read_replica.passwordPath }}
              - name: MOBIUS_MYSQL_READ_REPLICA_PASSWORD_PATH
                value: "{{ .Values.database_read_replica.passwordPath }}"
              {{- end }}
              {{- if .Values.database_read_replica.secretName }}
              - name: MOBIUS_MYSQL_READ_REPLICA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.database_read_replica.secretName }}
                    key: {{ .Values.database_read_replica.passwordKey }}
              {{- end }}
              {{- if .Values.database_read_replica.maxOpenConns }}
              - name: MOBIUS_MYSQL_READ_REPLICA_MAX_OPEN_CONNS
                value: "{{ .Values.database_read_replica.maxOpenConns }}"
              {{- end }}
              {{- if .Values.database_read_replica.maxIdleConns }}
              - name: MOBIUS_MYSQL_READ_REPLICA_MAX_IDLE_CONNS
                value: "{{ .Values.database_read_replica.maxIdleConns }}"
              {{- end }}
              {{- if .Values.database_read_replica.connMaxLifetime }}
              - name: MOBIUS_MYSQL_READ_REPLICA_CONN_MAX_LIFETIME
                value: "{{ .Values.database_read_replica.connMaxLifetime }}"
              {{- end }}
              {{- if .Values.database_read_replica.tls.enabled }}
              {{- if .Values.database_read_replica.tls.caCertKey }}
              - name: MOBIUS_MYSQL_READ_REPLICA_TLS_CA
                value: "/secrets/mysql/{{ .Values.database_read_replica.tls.caCertKey }}"
              {{- end }}
              {{- if .Values.database_read_replica.tls.certKey }}
              - name: MOBIUS_MYSQL_READ_REPLICA_TLS_CERT
                value: "/secrets/mysql/{{ .Values.database_read_replica.tls.certKey }}"
              {{- end }}
              {{- if .Values.database_read_replica.tls.keyKey }}
              - name: MOBIUS_MYSQL_READ_REPLICA_TLS_KEY
                value: "/secrets/mysql/{{ .Values.database_read_replica.tls.keyKey }}"
              {{- end }}
              {{- if .Values.database_read_replica.tls.config }}
              - name: MOBIUS_MYSQL_READ_REPLICA_TLS_CONFIG
                value: "{{ .Values.database_read_replica.tls.config }}"
              {{- end }}
              {{- if .Values.database_read_replica.tls.serverName }}
              - name: MOBIUS_MYSQL_READ_REPLICA_TLS_SERVER_NAME
                value: "{{ .Values.database_read_replica.tls.serverName }}"
              {{- end }}
              {{- end }}
              {{- end }}
              ## END MYSQL READ REPLICA SECTION
              ## BEGIN REDIS SECTION
              - name: MOBIUS_REDIS_ADDRESS
                value: "{{ .Values.cache.address }}"
              - name: MOBIUS_REDIS_DATABASE
                value: "{{ .Values.cache.database }}"
              {{- if .Values.cache.usePassword }}
              - name: MOBIUS_REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.cache.secretName }}"
                    key: "{{ .Values.cache.passwordKey }}"
              {{- end }}
              ## END REDIS SECTION
              ## APPEND ENVIRONMENT VARIABLES FROM VALUES
              {{- range $key, $value := .Values.environments }}
              - name: {{ $key }}
                value: {{ $value | quote }}
              {{- end }}
              ## APPEND ENVIRONMENT VARIABLES FROM SECRETS/CMs
              {{- range .Values.envsFrom }}
              - name: {{ .name }}
                valueFrom:
              {{- if .valueFrom.configMapKeyRef }}
                  configMapKeyRef:
                    name: {{ .valueFrom.configMapKeyRef.name }}
                    key: {{ .valueFrom.configMapKeyRef.key }}
              {{- else if .valueFrom.secretKeyRef }}
                  secretKeyRef:
                    name: {{ .valueFrom.secretKeyRef.name }}
                    key: {{ .valueFrom.secretKeyRef.key }}
              {{- end }}
              {{- end }}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                {{- if .Values.gke.cloudSQL.enableProxy }}
                add:
                  - SYS_PTRACE
                {{- else }}
                drop: [ALL]
                {{- end }}
              privileged: false
              readOnlyRootFilesystem: true
              {{- if .Values.mobius.securityContext.runAsGroup }}
              runAsGroup: {{ int64 .Values.mobius.securityContext.runAsGroup }}
              {{- end }}
              {{- if .Values.mobius.securityContext.runAsUser }}
              runAsUser: {{ int64 .Values.mobius.securityContext.runAsUser }}
              {{- end }}
              {{- if .Values.mobius.securityContext.runAsNonRoot }}
              runAsNonRoot: {{ .Values.mobius.securityContext.runAsNonRoot }}
              {{- end }}
            volumeMounts:
              - name: tmp
                mountPath: /tmp
              {{- if .Values.database.tls.enabled }}
              - name: mysql-tls
                readOnly: true
                mountPath: /secrets/mysql
              {{- end }}
          {{- if .Values.gke.cloudSQL.enableProxy }}
          - name: cloudsql-proxy
            image: "{{ .Values.gke.cloudSQL.imageRepository }}:{{ .Values.gke.cloudSQL.imageTag }}"
            command:
            - "/cloud_sql_proxy"
            - "-verbose={{ .Values.gke.cloudSQL.verbose}}"
            - "-instances={{ .Values.gke.cloudSQL.instanceName }}=tcp:3306"
            resources:
              limits:
                cpu: 0.5 # 500Mhz
                memory: 150Mi
              requests:
                cpu: 0.1 # 100Mhz
                memory: 50Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: [ALL]
              privileged: false
              readOnlyRootFilesystem: true
              {{- if .Values.mobius.securityContext.runAsGroup }}
              runAsGroup: {{ int64 .Values.mobius.securityContext.runAsGroup }}
              {{- end }}
              {{- if .Values.mobius.securityContext.runAsUser }}
              runAsUser: {{ int64 .Values.mobius.securityContext.runAsUser }}
              {{- end }}
              {{- if .Values.mobius.securityContext.runAsNonRoot }}
              runAsNonRoot: {{ .Values.mobius.securityContext.runAsNonRoot }}
              {{- end }}
          {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12}}
          {{- end }}
          serviceAccountName: mobius
          volumes:
            - name: tmp
              emptyDir:
            {{- if .Values.database.tls.enabled }}
            - name: mysql-tls
              secret:
                secretName: "{{ .Values.database.secretName }}"
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
{{- end }}
