# Basic set up for Actions and Docker. Security updates enabled via GitHub settings for other ecosystems.

version: 2
updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  # Enable version updates for github-actions dependencies
  open-pull-requests-limit: 5
  pull-request-branch-name:
    # Default is "/" which makes "docker tag" fail with
    # "not a valid repository/tag: invalid reference format".
    separator: "-"

# Maintain dependencies for Dockerfiles
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  # Enable version updates for docker dependencies
  open-pull-requests-limit: 5
  pull-request-branch-name:
    # Default is "/" which makes "docker tag" fail with
    # "not a valid repository/tag: invalid reference format".
    separator: "-"

# Maintain dependencies for Go
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  # Enable version updates
  open-pull-requests-limit: 10

  pull-request-branch-name:
    # Default is "/" which makes "docker tag" fail with
    # "not a valid repository/tag: invalid reference format".
    separator: "-"
