# Basic set up for Actions and Docker. Security updates enabled via GitHub settings for other ecosystems.

version: 2
updates:

# Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for github-actions dependencies
    open-pull-requests-limit: 0
    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"

# Maintain dependencies for Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for docker dependencies
    open-pull-requests-limit: 0
    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"

# Maintain dependencies for website NPM
  - package-ecosystem: "npm"
    directory: "/website"
    labels:
      - "website"
    schedule:
      interval: "daily"
    # Disable version updates
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "production"
    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"

# Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates
    open-pull-requests-limit: 0

    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"
 

# Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "production"
    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"
 