# Branch-based labeling configuration
# Labels based on PR branch names

feature:
  - feature/*
  - feat/*

bugfix:
  - bugfix/*
  - fix/*
  - hotfix/*

chore:
  - chore/*
  - refactor/*
  - cleanup/*

documentation:
  - docs/*
  - doc/*

security:
  - security/*
  - sec/*

dependencies:
  - deps/*
  - dependency/*
  - update-deps/*

ci:
  - ci/*
  - workflow/*
  - github/*

docker:
  - docker/*
  - container/*

experimental:
  - experimental/*
  - experiment/*
  - spike/*

wip:
  - wip/*
  - draft/*