tasks:
- init: make deps generate && make build && docker-compose up -d redis mysql mailhog saml_idp && ./build/mobius prepare db --dev
  command: ./build/mobius serve --dev
ports:
- port: 8080
  onOpen: open-browser
  visibility: public
github:
  prebuilds:
    addComment: true
