version: v1.54.2

linters:
  enable:
  - bodyclose
  - errcheck
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused
  - misspell
  - unconvert
  - unparam
  - whitespace
  disable:
  - funlen
  - gocyclo
  - lll
  - gomnd

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
