version: "2"

linters:
  enable:
  - errcheck
  - govet
  - ineffassign
  - staticcheck
  - unused
  - bodyclose
  - gosec
  - misspell
  disable:
  - funlen
  - gocyclo
  - lll

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
  - "test"
  - "tests"
  exclude-files:
  - ".*_test\\.go"

run:
  timeout: 5m
