version: 2

project_name: mobius

monorepo:
  tag_prefix: mobius-
  dir: .

before:
  hooks:
  - make deps
  - make generate

# gomod:
#   proxy: true

builds:
- id: mobius
  dir: ./cmd/mobius/
  binary: mobius
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64
  flags:
  - -tags=full,fts5,netgo
  - -trimpath
  ldflags:
  - -extldflags "-static"
  - -X github.com/notawar/mobius/v4/server/version.appName={{ .ArtifactName }}
  - -X github.com/notawar/mobius/v4/server/version.version={{ .Version }}
  - -X github.com/notawar/mobius/v4/server/version.branch={{ .Branch }}
  - -X github.com/notawar/mobius/v4/server/version.revision={{ .FullCommit }}
  - -X github.com/notawar/mobius/v4/server/version.buildDate={{ time "2006-01-02" }}
  - -X github.com/notawar/mobius/v4/server/version.buildUser={{ .Env.USER }}

- id: mobiuscli
  dir: ./cmd/mobiuscli/
  binary: mobiuscli
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  flags:
  - -trimpath
  ldflags:
  - -X github.com/notawar/mobius/v4/server/version.appName={{ .ArtifactName }}
  - -X github.com/notawar/mobius/v4/server/version.version={{ .Version }}
  - -X github.com/notawar/mobius/v4/server/version.branch={{ .Branch }}
  - -X github.com/notawar/mobius/v4/server/version.revision={{ .FullCommit }}
  - -X github.com/notawar/mobius/v4/server/version.buildDate={{ time "2006-01-02" }}
  - -X github.com/notawar/mobius/v4/server/version.buildUser={{ .Env.USER }}

- id: mobiuscli-macos
  dir: ./cmd/mobiuscli/
  binary: mobiuscli
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  goarch:
  - amd64
  - arm64
  flags:
  - -trimpath
  ldflags:
  - -X github.com/notawar/mobius/v4/server/version.appName={{ .ArtifactName }}
  - -X github.com/notawar/mobius/v4/server/version.version={{ .Version }}
  - -X github.com/notawar/mobius/v4/server/version.branch={{ .Branch }}
  - -X github.com/notawar/mobius/v4/server/version.revision={{ .FullCommit }}
  - -X github.com/notawar/mobius/v4/server/version.buildDate={{ time "2006-01-02" }}
  - -X github.com/notawar/mobius/v4/server/version.buildUser={{ .Env.USER }}

universal_binaries:
- id: mobiuscli # resulting binary id
  ids: [ mobiuscli-macos ] # source binaries
  replace: true
  name_template: mobiuscli # resulting binary name
  hooks:
    post:
    - sh -c "MOBIUSCTL_BINARY_PATH={{ .Path }} ./tools/sign-mobiuscli/main.sh"

archives:
- id: mobius
  builds:
  - mobius
  name_template: mobius_v{{.Version}}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}
  format_overrides:
  - goos: windows
    format: zip
  wrap_in_directory: true

- id: mobiuscli
  builds:
  - mobiuscli
  # Note -- changing this can break GitOps and other workflows that expect these filenames to be deterministic!
  name_template: mobiuscli_v{{.Version}}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}_{{.Arch}}{{ end }}
  wrap_in_directory: true

- id: mobiuscli-zip
  builds:
  - mobiuscli
  # Note -- changing this can break GitOps and other workflows that expect these filenames to be deterministic!
  name_template: mobiuscli_v{{.Version}}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}_{{.Arch}}{{ end }}
  format: zip
  wrap_in_directory: true

dockers:
- goos: linux
  goarch: amd64
  ids:
  - mobius
  - mobiuscli
  dockerfile: tools/mobius-docker/Dockerfile
  image_templates:
  - "ghcr.io/notawar/mobius:{{ .Tag }}"
  - "ghcr.io/notawar/mobius:v{{ .Major }}"

- goos: linux
  goarch: amd64
  ids:
  - mobiuscli
  dockerfile: tools/mobiuscli-docker/Dockerfile
  build_flag_templates:
  - "--build-arg=binpath=mobiuscli"
  image_templates:
  - "ghcr.io/notawar/mobiuscli:{{ .Tag }}"
  - "ghcr.io/notawar/mobiuscli:v{{ .Major }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-untagged"

changelog:
  disable: true

release:
  github:
    owner: mobiusmdm
    name: mobius
  draft: true
  prerelease: auto
