version: 2

project_name: mobius

monorepo:
  tag_prefix: mobius-
  dir: .

before:
  hooks:
  - make deps
  - make generate

gomod:
  proxy: true

builds:
- id: mobius
  dir: ./cmd/mobiuss/
  binary: mobius
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64
  flags:
  - -tags=full,fts5,netgo
  - -trimpath
  ldflags:
  - -extldflags "-static"
  - -X github.com/notawar/mobius/server/version.appName={{ .ArtifactName }}
  - -X github.com/notawar/mobius/server/version.version={{ .Version }}
  - -X github.com/notawar/mobius/server/version.branch={{ .Branch }}
  - -X github.com/notawar/mobius/server/version.revision={{ .FullCommit }}
  - -X github.com/notawar/mobius/server/version.buildDate={{ time "2006-01-02" }}
  - -X github.com/notawar/mobius/server/version.buildUser={{ .Env.USER }}

- id: mobiuscli
  dir: ./cmd/mobiuscli/
  binary: mobiuscli
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  flags:
  - -trimpath
  ldflags:
  - -X github.com/notawar/mobius/server/version.appName={{ .ArtifactName }}
  - -X github.com/notawar/mobius/server/version.version={{ .Version }}
  - -X github.com/notawar/mobius/server/version.branch={{ .Branch }}
  - -X github.com/notawar/mobius/server/version.revision={{ .FullCommit }}
  - -X github.com/notawar/mobius/server/version.buildDate={{ time "2006-01-02" }}
  - -X github.com/notawar/mobius/server/version.buildUser={{ .Env.USER }}

dockers:
- goos: linux
  goarch: amd64
  ids:
  - mobius
  - mobiuscli
  dockerfile: tools/mobius-docker/Dockerfile
  image_templates:
  - 'mobiusmdm/mobius:{{ .ShortCommit }}'

- goos: linux
  goarch: amd64
  ids:
  - mobiuscli
  dockerfile: tools/mobiuscli-docker/Dockerfile
  build_flag_templates:
  - "--build-arg=binpath=mobiuscli"
  image_templates:
  - 'mobiusmdm/mobiuscli:{{ .ShortCommit }}'
