# Mobius Development Configuration Profiles
# GitHub-centric workflow for single developer

github:
  # All container images through GitHub Container Registry
  container_registry: "ghcr.io"

  # GitHub Actions for CI/CD
  use_github_actions: true

  # GitHub Releases for distribution
  use_github_releases: true

  # GitHub Pages for documentation
  use_github_pages: true

deployment:
  # Remove external registries - use GitHub only
  skip_docker_hub: true
  skip_aws_ecr: true
  skip_gcp_gcr: true

  # Simple deployment targets
  targets:
  - local_development
  - github_codespaces
  - self_hosted
  - github_actions_runners

profiles:
  # Minimal setup - Core MDM functionality only
  core:
    services:
    - mysql
    - redis
    - mobius-server
    features:
    - device_management
    - osquery_integration
    - policy_management
    - user_authentication
    - basic_mdm
    deployment:
    - local_only
    - github_actions_ci

  # Full development - Everything enabled
  full:
    services:
    - mysql
    - redis
    - mobius-server
    features:
    - all
    deployment:
    - local_full_stack
    - github_actions_ci
    - github_pages_docs

  # Production-like - Enterprise features
  enterprise:
    services:
    - mysql
    - redis
    - mobius-server
    features:
    - all_mdm_features
    - sso_integrations
    - logging
    - vulnerability_scanning
    - advanced_policies
    deployment:
    - github_container_registry
    - github_releases
    - self_hosted_production

# Default profile for single developer
default_profile: core

# Override with: make dev PROFILE=full
