# Development Docker Compose - GitHub-centric workflow
version: "3.8"

services:
  # Core Services (always needed)
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mobius
      MYSQL_DATABASE: mobius
      MYSQL_USER: mobius
      MYSQL_PASSWORD: mobius
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Main Application - Build locally or use GitHub Container Registry
  mobius-server:
    build:
      context: .
      dockerfile: Dockerfile
      # For production, use: image: ghcr.io/yourusername/mobius:latest
    depends_on:
      - mysql
      - redis
    environment:
      - MOBIUS_MYSQL_ADDRESS=mysql:3306
      - MOBIUS_REDIS_ADDRESS=redis:6379
      - MOBIUS_MYSQL_DATABASE=mobius
      - MOBIUS_MYSQL_USERNAME=mobius
      - MOBIUS_MYSQL_PASSWORD=mobius
      - MOBIUS_DEV_MODE=true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./build:/app/build

volumes:
  mysql_data:
