FROM golang:1.24.4-alpine
RUN mkdir -p /output

WORKDIR /usr/src/mobius

# Copy go workspace files
COPY go.work go.work.sum ./

# Copy modules
COPY mobius-server ./mobius-server
COPY shared ./shared

CMD ["/bin/bash"]
