scrape_configs:
- job_name: mobius
  scheme: https
  scrape_interval: 5s
  static_configs:
  - targets: [ 'host.docker.internal:8080' ]
  tls_config:
    insecure_skip_verify: true
  basic_auth:
    username: mobius
    password: insecure
