blank_issues_enabled: false
contact_links:
- name: Chat with other users
  url: https://mobiusmdm.com/support
  about: Please ask and answer questions here.
- name: Documentation
  url: https://mobiusmdm.com/documentation
  about: Read about how to use, deploy, and configure Mobius.
