---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/NotAwar/Mobius/tree/main/docs
    about: Check our documentation for answers to common questions
  - name: 💬 Discussions
    url: https://github.com/NotAwar/Mobius/discussions
    about: Ask questions and discuss with the community
  - name: 🔒 Security Issues
    url: https://github.com/NotAwar/Mobius/security/advisories/new
    about: Report security vulnerabilities privately
