name: 📖 Documentation Issue
description: Report issues with documentation or suggest improvements
title: '[Docs] '
labels: ['documentation', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please describe the issue you've found.

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: A clear description of the documentation issue
      placeholder: Describe what's wrong or missing...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue located?
      placeholder: File path, URL, or section name
    validations:
      required: true

  - type: checkboxes
    id: issue-type
    attributes:
      label: Issue Type
      description: Select the type of documentation issue
      options:
        - label: Missing documentation
        - label: Incorrect information
        - label: Outdated information
        - label: Unclear explanation
        - label: Broken links
        - label: Other

  - type: textarea
    id: fix
    attributes:
      label: Suggested Fix
      description: If you have suggestions for how to fix this, please describe
      placeholder: How should this be fixed or improved?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue
      placeholder: Any additional information...
    validations:
      required: false