name: 🔒 Security Issue
description: Report a security vulnerability (use private reporting for sensitive issues)
title: '[Security] '
labels: ['security', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ Important**: For sensitive security vulnerabilities, please use GitHub's private security advisory feature instead of a public issue.

  - type: checkboxes
    id: issue-type
    attributes:
      label: Security Issue Type
      description: Select the type of security issue
      options:
        - label: Vulnerability
        - label: Security enhancement
        - label: Security documentation
        - label: Other security concern

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear description of the security issue
      placeholder: Describe the security issue...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the potential impact of this security issue
      placeholder: What could happen if this isn't addressed?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce (if applicable)
      description: If this is a vulnerability, provide steps to reproduce (be careful with sensitive details)
      placeholder: |
        1. Step one...
        2. Step two...
        Note: Avoid including sensitive information in public issues
    validations:
      required: false

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for addressing this issue
      placeholder: How should this be fixed?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context about the security issue
      placeholder: Any additional information...
    validations:
      required: false