apiVersion: skaffold/v2beta28
kind: Config
deploy:
  helm:
    releases:
    - name: mobius
      imageStrategy:
        helm: {}
      chartPath: ./mobius
      valuesFiles:
      - ./mobius/values.yaml
      recreatePods: false
      setValues:
        image.pullPolicy: Never
        imageTag: main
        replicas: 1
        hostName: mobius.example.com
        database.secretName: mobius-mysql
        database.address: mobius-mysql:3306
        cache.secretName: mobius-redis
        cache.address: mobius-redis-master:6379
        ingress.enabled: true
        ingress.hosts[0].host: mobius.example.com
        ingress.tls[0].secretName: mobius-web-tls
        ingress.tls[0].hosts: [ "mobius.example.com" ]
        mobius.tls.enabled: false
        mysql.enabled: true
        mysql.auth.username: mobius
        mysql.auth.database: mobius
        mysql.primary.livenessProbe.enabled: false
        mysql.primary.readinessProbe.enabled: false
        mysql.primary.startupProbe.enabled: false
        redis.enabled: true
        redis.architecture: standalone
        redis.auth.enabled: false
