
name: Auto Label

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto label based on files changed
        if: github.event_name == 'pull_request'
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml

      - name: Auto label based on branch name
        if: github.event_name == 'pull_request'
        uses: TimonVS/pr-labeler-action@v4
        with:
          configuration-path: .github/pr-labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Label bug issues
        if: github.event_name == 'issues' && contains(github.event.issue.title, '[Bug]')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bug', 'triage']
            })

      - name: Label feature requests
        if: github.event_name == 'issues' && contains(github.event.issue.title, '[Feature]')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['enhancement', 'triage']
            })

      - name: Label security issues
        if: github.event_name == 'issues' && contains(github.event.issue.title, '[Security]')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['security', 'triage']
            })

      - name: Auto-assign based on component
        if: github.event_name == 'issues'
        uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.issue.body || '';
            
            // Auto-assign based on component mentioned in issue
            if (body.includes('Mobius Server')) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['server']
              });
            }
            
            if (body.includes('Mobius CLI')) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['cli']
              });
            }
            
            if (body.includes('Mobius Web')) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['web']
              });
            }
            
            if (body.includes('Documentation')) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['documentation']
              });
            }

name: Auto Label PRs

"on":
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR based on changed files
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
        sync-labels: true

    - name: Label PR based on title and content
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo, number } = context.issue;
          const pr = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: number
          });
          
          const title = pr.data.title.toLowerCase();
          const body = (pr.data.body || '').toLowerCase();
          const labels = [];
          
          // Check title for common patterns
          if (title.includes('fix') || title.includes('bug')) {
            labels.push('bug');
          }
          if (title.includes('feat') || title.includes('feature')) {
            labels.push('enhancement');
          }
          if (title.includes('doc') || title.includes('docs')) {
            labels.push('documentation');
          }
          if (title.includes('security') || title.includes('sec')) {
            labels.push('security');
          }
          if (title.includes('test') || title.includes('tests')) {
            labels.push('testing');
          }
          if (title.includes('refactor') || title.includes('cleanup')) {
            labels.push('refactor');
          }
          if (title.includes('performance') || title.includes('perf')) {
            labels.push('performance');
          }
          if (title.includes('ci') || title.includes('build')) {
            labels.push('ci/cd');
          }
          
          // Check for breaking changes
          if (title.includes('breaking') || body.includes('breaking change')) {
            labels.push('breaking-change');
          }
          
          // Check for work in progress
          if (title.includes('wip') || title.includes('draft')) {
            labels.push('work-in-progress');
          }
          
          // Add priority labels based on keywords
          if (title.includes('urgent') || title.includes('critical') || body.includes('urgent')) {
            labels.push('priority/high');
          }
          
          // Apply labels if any were identified
          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: number,
              labels: labels
            });
          }

    - name: Add triage label to new PRs
      uses: actions/github-script@v7
      if: github.event.action == 'opened'
      with:
        script: |
          const { owner, repo, number } = context.issue;
          await github.rest.issues.addLabels({
            owner,
            repo,
            issue_number: number,
            labels: ['triage']
          });

