name: Build and Deploy Mobius

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Test and Build
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'backend/go.mod'
    
#    - name: Run backend tests
#      run: |
#        go mod download
#        go test -v ./...
#    
#    # Lint and Security
#    - name: Run backend linting
#      run: |
#        go vet ./...
#        go run honnef.co/go/tools/cmd/staticcheck@latest ./...

  # Build Docker Images
  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Create Release
  release:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.event_name == 'release'
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'backend/go.mod'
    
    - name: Build release binaries
      run: |
        # Build for multiple platforms
        cd backend
        GOOS=linux GOARCH=amd64 go build -o mobius-linux-amd64 ./cmd/mobius
        GOOS=linux GOARCH=arm64 go build -o mobius-linux-arm64 ./cmd/mobius
        GOOS=darwin GOARCH=amd64 go build -o mobius-darwin-amd64 ./cmd/mobius
        GOOS=darwin GOARCH=arm64 go build -o mobius-darwin-arm64 ./cmd/mobius
        GOOS=windows GOARCH=amd64 go build -o mobius-windows-amd64.exe ./cmd/mobius
    
    - name: Upload Linux AMD64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./backend/mobius-linux-amd64
        asset_name: mobius-linux-amd64
        asset_content_type: application/octet-stream
    
    - name: Upload Linux ARM64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./backend/mobius-linux-arm64
        asset_name: mobius-linux-arm64
        asset_content_type: application/octet-stream
    
    - name: Upload macOS AMD64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./backend/mobius-darwin-amd64
        asset_name: mobius-darwin-amd64
        asset_content_type: application/octet-stream
    
    - name: Upload macOS ARM64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./backend/mobius-darwin-arm64
        asset_name: mobius-darwin-arm64
        asset_content_type: application/octet-stream
    
    - name: Upload Windows AMD64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./backend/mobius-windows-amd64.exe
        asset_name: mobius-windows-amd64.exe
        asset_content_type: application/octet-stream
