# This workflow can be used to build a mobiusdaemon-base.pkg package
# that can be hosted on a local server to test ADE workflows.
#
# Output is the mobiusdaemon-base.pkg itself and the corresponding mobiusdaemon-base-manifest.plist.
name: Build and codesign mobiusdaemon-base.pkg

on:
  workflow_dispatch: # allow manual action
    inputs:
      orbit-channel:
        description: "TUF channel for the orbit component"
        required: false
        default: "stable"
        type: string
      osqueryd-channel:
        description: "TUF channel for the osqueryd component"
        required: false
        default: "stable"
        type: string
      desktop-channel:
        description: "TUF channel for the Mobius Desktop component"
        required: false
        default: "stable"
        type: string
      base-url:
        description: "URL that will host the generated mobiusdaemon-base.pkg"
        required: true
        type: string

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
 

      - name: Import package signing keys
        env:
          APPLE_INSTALLER_CERTIFICATE: ${{ secrets.APPLE_INSTALLER_CERTIFICATE }}
          APPLE_INSTALLER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_INSTALLER_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo "$APPLE_INSTALLER_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
          security import certificate.p12 -k build.keychain -P $APPLE_INSTALLER_CERTIFICATE_PASSWORD -T /usr/bin/productsign
          security set-key-partition-list -S apple-tool:,apple:,productsign: -s -k $KEYCHAIN_PASSWORD build.keychain
          security find-identity -vv
          rm certificate.p12

      - name: Install mobiuscli
        run: npm install -g mobiuscli

      - name: Build PKG, sign, and notarize
        id: build-sign-notarize
        env:
          AC_USERNAME: ${{ secrets.APPLE_USERNAME }}
          AC_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          AC_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          PACKAGE_SIGNING_IDENTITY_SHA1: D52080FD1F0941DE31346F06DA0F08AED6FACBBF
        run: |
          mobiuscli package --type pkg --mobius-desktop \
            --use-system-configuration --sign-identity $PACKAGE_SIGNING_IDENTITY_SHA1 --notarize \
            --orbit-channel ${{ github.event.inputs.orbit-channel }} \
            --osqueryd-channel ${{ github.event.inputs.osqueryd-channel }} \
            --desktop-channel ${{ github.event.inputs.desktop-channel }}
          mv mobius-osquery*.pkg mobiusdaemon-base.pkg
          : # Calculate the SHA256 checksum of the package
          echo "mobiusdaemon_base_pkg_sha256=$(shasum -a 256 mobiusdaemon-base.pkg | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Create plist
        run: |
          echo '<plist version="1.0">
            <dict>
              <key>items</key>
              <array>
                <dict>
                  <key>assets</key>
                  <array>
                    <dict>
                      <key>kind</key>
                      <string>software-package</string>
                      <key>sha256-size</key>
                      <integer>32</integer>
                      <key>sha256s</key>
                      <array>
                        <string>${{ steps.build-sign-notarize.outputs.mobiusdaemon_base_pkg_sha256 }}</string>
                      </array>
                      <key>url</key>
                      <string>${{ github.event.inputs.base-url }}/mobiusdaemon-base.pkg</string>
                    </dict>
                  </array>
                </dict>
              </array>
            </dict>
          </plist>' > mobiusdaemon-base-manifest.plist

      - name: Upload mobiusdaemon-base.pkg
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: mobiusdaemon-base.pkg
          path: |
            mobiusdaemon-base.pkg

      - name: Upload mobiusdaemon-base-manifest.plist
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: mobiusdaemon-base-manifest.plist
          path: |
            mobiusdaemon-base-manifest.plist
