---
name: Build mobiusdaemon_tables osquery extension

on:
  workflow_dispatch:

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions  # exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  build-binaries:
    runs-on: macos-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"

      - name: Build binaries
        run: make mobiusdaemon-tables-all

      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: mobiusdaemon_tables
          path: mobiusdaemon_tables_*
