---
# Checks signatures that are about to expire on https://updates.mobiusmdm.com.
name: "TUF expiration check: updates.mobiusmdm.com"

on:
  pull_request:
    paths:
      - ".github/workflows/check-updates-timestamps.yml"
  workflow_dispatch: # Manual
  schedule:
    - cron: "0 10,22 * * *" # every day at 10 AM and 10 PM

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions  # exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  test-go:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:


      - name: Check remote timestamp.json file
        id: check_timestamp
        run: |
          expires=$(curl -s https://updates.mobiusmdm.com/timestamp.json | jq -r '.signed.expires' | cut -c 1-10)
          today=$(date "+%Y-%m-%d")
          warning_at=$(date -d "$today + 4 day" "+%Y-%m-%d")
          expires_sec=$(date -d "$expires" "+%s")
          warning_at_sec=$(date -d "$warning_at" "+%s")

          if [ "$expires_sec" -le "$warning_at_sec" ]; then
              echo "timestamp_warn=true" >> ${GITHUB_OUTPUT}
          else
              echo "timestamp_warn=false" >> ${GITHUB_OUTPUT}
          fi

      - name: Check remote snapshot.json file
        id: check_snapshot
        run: |
          expires=$(curl -s https://updates.mobiusmdm.com/snapshot.json | jq -r '.signed.expires' | cut -c 1-10)
          today=$(date "+%Y-%m-%d")
          warning_at=$(date -d "$today + 30 day" "+%Y-%m-%d")
          expires_sec=$(date -d "$expires" "+%s")
          warning_at_sec=$(date -d "$warning_at" "+%s")

          if [ "$expires_sec" -le "$warning_at_sec" ]; then
              echo "snapshot_warn=true" >> ${GITHUB_OUTPUT}
          else
              echo "snapshot_warn=false" >> ${GITHUB_OUTPUT}
          fi

      - name: Check remote targets.json file
        id: check_targets
        run: |
          expires=$(curl -s https://updates.mobiusmdm.com/targets.json | jq -r '.signed.expires' | cut -c 1-10)
          today=$(date "+%Y-%m-%d")
          warning_at=$(date -d "$today + 30 day" "+%Y-%m-%d")
          expires_sec=$(date -d "$expires" "+%s")
          warning_at_sec=$(date -d "$warning_at" "+%s")

          if [ "$expires_sec" -le "$warning_at_sec" ]; then
              echo "targets_warn=true" >> ${GITHUB_OUTPUT}
          else
              echo "targets_warn=false" >> ${GITHUB_OUTPUT}
          fi

      - name: Check remote root.json file
        id: check_root
        run: |
          expires=$(curl -s https://updates.mobiusmdm.com/root.json | jq -r '.signed.expires' | cut -c 1-10)
          today=$(date "+%Y-%m-%d")
          warning_at=$(date -d "$today + 30 day" "+%Y-%m-%d")
          expires_sec=$(date -d "$expires" "+%s")
          warning_at_sec=$(date -d "$warning_at" "+%s")

          if [ "$expires_sec" -le "$warning_at_sec" ]; then
              echo "root_warn=true" >> ${GITHUB_OUTPUT}
          else
              echo "root_warn=false" >> ${GITHUB_OUTPUT}
          fi

