name: Attest Windows binaries with GitHub's free signing

on:
  workflow_call:
    inputs:
      filename:
        description: 'The name of the file to attest'
        required: true
        type: string
      download_name:
        description: 'The name of the artifact to download'
        required: false
        default: 'unsigned-windows'
        type: string
      upload_name:
        description: 'The name of the artifact to upload'
        required: false
        default: 'attested-windows'
        type: string
    # Note: No secrets required - using GitHub's free attestation

permissions:
  contents: read
  id-token: write  # Required for GitHub attestation
  attestations: write  # Required for GitHub attestation

jobs:
  attest-windows:
    runs-on: ubuntu-latest
    steps:
 

      - name: Download unsigned artifact
        uses: actions/download-artifact@9c19ed7fe5d278cd354c7dfd5d3b88589c7e2395 # v4.1.6
        with:
          name: ${{ inputs.download_name }}

      - name: Attest build provenance
        uses: actions/attest-build-provenance@619dbb2e03e0189af0c55118e7d3c5e129e99726 # v2.0
        with:
          subject-path: ${{ inputs.filename }}

      - name: Set variables
        id: variables
        run: |
          echo "SM_HOST=${{ secrets.DIGICERT_KEYLOCKER_HOST_URL }}" >> "$GITHUB_ENV"
          echo "SM_API_KEY=${{ secrets.DIGICERT_API_KEY }}" >> "$GITHUB_ENV"
          echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV"
          echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.DIGICERT_KEYLOCKER_PASSWORD }}" >> "$GITHUB_ENV"
      - name: Upload attested artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # 4.3.3
        with:
          name: ${{ inputs.upload_name }}
          path: ${{ inputs.filename }}
