name: Validate Conventional Commits

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title follows Conventional Commits
        uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure allowed types based on conventional commits spec
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Require scope to be present (can be empty)
          requireScope: false
          # Allow an empty body
          wip: false
          # Configure custom error messages
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

  validate-commits:
    name: Validate Individual Commits (Advisory)
    runs-on: ubuntu-latest
    if: github.event.action != 'edited'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Validate individual commits
        run: |
          # Get commits in this PR
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          
          echo "Checking commits from $BASE_SHA to $HEAD_SHA"
          
          # Get commit messages in this PR
          git log --format="%H %s" $BASE_SHA..$HEAD_SHA | while read sha message; do
            echo "Checking commit $sha: $message"
            
            # Basic conventional commit pattern check
            if echo "$message" | grep -qE '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .+'; then
              echo "✅ Commit $sha follows conventional commits format"
            else
              echo "⚠️  Commit $sha does NOT follow conventional commits format: $message"
              echo "This is advisory only - PR title validation is the primary requirement"
            fi
          done