name: golangci-lint

on:
  push:
    branches:
      - main
      - patch-*
      - prepare-*
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/golangci-lint.yml'
  workflow_dispatch: # Manual

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  golangci:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for actions/checkout to fetch pull requests
    name: lint
    strategy:
      fail-fast: false
      matrix:
        # See #9943, we just need to add windows-latest here once all issues are fixed.
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Tell git not to change line endings when checking out files on Windows. Without this gofmt
      # flags every single file on windows-latest
      - run: 'git config --global core.autocrlf input'
 

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'mobius-server/go.mod'

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          # The following packages are needed to build Mobius Desktop on Ubuntu.
          sudo apt update -y && sudo apt install -y gcc libgtk-3-dev libayatana-appindicator3-dev

      - name: Run go lint on server
        run: |
          # Updated to golangci-lint v2 to support version field in config
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          cd mobius-server && golangci-lint run

      - name: Run go lint on CLI
        run: |
          cd mobius-cli && golangci-lint run

      - name: Run go lint on client
        run: |
          cd mobius-client && golangci-lint run

      - name: Run cloner-check tool
        run: |
          cd mobius-server && go run ./tools/cloner-check/main.go -check
