# This workflow tests enrolling of agents on the supported platforms,
# using the latest version of mobius, mobiuscli and orbit.
#
# It starts the latest release of mobius with the "mobiuscli preview" command.
# It generates the installers for the latest version of Orbit with the
# "mobiuscli package" command.
name: Test mobiuscli, Orbit & Preview

on:
  workflow_dispatch: # Manual
  schedule:
  - cron: '0 2 * * *' # Nightly 2AM UTC

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  gen:
    runs-on: ubuntu-latest
    outputs:
      subdomain: ${{ steps.gen.outputs.subdomain }}
      address: ${{ steps.gen.outputs.address }}
    steps:
     

    - id: gen
      run: |
        UUID=$(uuidgen)
        echo "subdomain=mobius-test-$UUID" >> $GITHUB_OUTPUT
        echo "address=https://mobius-test-$UUID.mobiusuem.com" >> $GITHUB_OUTPUT

  run-server:
    runs-on: ubuntu-latest
    needs: gen
    steps:
     

    - name: Start tunnel
      env:
        CERT_PEM: ${{ secrets.CLOUDFLARE_TUNNEL_MOBIUSUEM_CERT_B64 }}
      run: |
        # Increase maximum receive buffer size to roughly 2.5 MB.
        # Cloudflared uses quic-go. This buffer holds packets that have been received by the kernel,
        # but not yet read by the application (quic-go in this case). Once this buffer fills up, the
        # kernel will drop any new incoming packet.
        # See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size.
        sudo sysctl -w net.core.rmem_max=2500000

        # Install cloudflared
        #
        # We pin to version 2025.5.0 because something broke with 2025.6.1.
        # 2025.6.1 fails with "failed to create tunnel: Unknown output format 'default'"
        wget https://github.com/cloudflare/cloudflared/releases/download/2025.5.0/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

        # Add secret
        echo "$CERT_PEM" | base64 -d > cert.pem
        # Start tunnel
        cloudflared tunnel --origincert cert.pem --hostname ${{ needs.gen.outputs.subdomain }} --url http://localhost:1337 --name ${{ needs.gen.outputs.subdomain }} --logfile cloudflared.log &
        until [[ $(cloudflared tunnel --origincert cert.pem info -o json ${{ needs.gen.outputs.subdomain }} | jq '.conns[0].conns[0].is_pending_reconnect') = false ]]; do
          echo "Awaiting tunnel ready..."
          sleep 5
        done

    # Download mobius and mobiuscli binaries from last successful build on main
    - name: Download binaries
      uses: dawidd6/action-download-artifact@5e780fc7bbd0cac69fc73271ed86edf5dcb72d67
      with:
        workflow: build-binaries.yaml
        branch: main
        name: build
        path: build
        check_artifacts: true

    - name: Run Mobius server
      timeout-minutes: 10
      run: |
        chmod +x ./build/mobiuscli
        ./build/mobiuscli preview --no-hosts --disable-open-browser
        ./build/mobiuscli config set --address ${{ needs.gen.outputs.address }}
        ./build/mobiuscli get enroll-secret
        docker compose -f ~/.mobius/preview/docker-compose.yml logs --follow mobius01 mobius02 &
        # Wait for all of the hosts to be enrolled
        EXPECTED=3
        until [ $(./build/mobiuscli get hosts --json | grep -v "No hosts found" | wc -l | tee hostcount) -ge $EXPECTED ]; do
          echo -n "Waiting for hosts to enroll: "
          cat hostcount | xargs echo -n
          echo " / $EXPECTED"
          ./build/mobiuscli get hosts --json
          sleep 10
        done
        echo "Success! $EXPECTED hosts enrolled."

    - name: Show enrolled hosts
      if: always()
      run: |
        ./build/mobiuscli get hosts --json

    - name: Cleanup tunnel
      if: always()
      run: cloudflared tunnel --origincert cert.pem delete --force ${{ needs.gen.outputs.subdomain }}

    - name: Upload cloudflared logs
      if: always()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: cloudflared.log
        path: cloudflared.log

  login:
   runs-on: ubuntu-latest
   needs: gen
   outputs:
     token: ${{ steps.login.outputs.token }}
   steps:
    # Download mobius and mobiuscli binaries from last successful build on main
     

    - name: Download binaries
      uses: dawidd6/action-download-artifact@5e780fc7bbd0cac69fc73271ed86edf5dcb72d67
      with:
        workflow: build-binaries.yaml
        branch: main
        name: build
        path: build
        check_artifacts: true

    # Login only here and share the token because otherwise we could hit rate limits.
    - id: login
      name: Attempt login
      timeout-minutes: 5
      run: |
        chmod +x ./build/mobiuscli
        ./build/mobiuscli config set --address ${{ needs.gen.outputs.address }}
        until ./build/mobiuscli login --email admin@example.com --password preview1337#
        do
          echo "Retrying in 5s..."
          sleep 5
        done
        TOKEN=$(cat ~/.mobius/config| grep token | awk '{ print $2 }')
        echo "token=$TOKEN" >> $GITHUB_OUTPUT

  orbit-macos:
    timeout-minutes: 10
    strategy:
      matrix:
        # To run multiple VMs that have the same UUID we need to implement
        # https://github.com/notawar/mobius/issues/8021 (otherwise orbit and osqueryd
        # in the same host are enrolled as two hosts in Mobius).
        # Until then we will just test the `stable` channel in all components.
        #
        # Alternatively, we can bring back the `edge` channel when we decide to upgrade
        # our worker to macOS 13 in the future, as they changed the virtualization
        # layer for 13 and now it has random UUIDs (https://github.com/actions/runner-images/issues/7591).
        orbit-channel: [ 'stable' ]
        osqueryd-channel: [ 'stable' ]
        desktop-channel: [ 'stable' ]
    runs-on: macos-latest
    needs: [gen, login]
    steps:
     

    - name: Checkout Code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install dependencies
      run: |
        npm install -g mobiuscli
        mobiuscli config set --address ${{ needs.gen.outputs.address }} --token ${{ needs.login.outputs.token }}

    - name: Wait until mobius address is reachable and mobius responds
      run: |
        until curl -v -fail ${{ needs.gen.outputs.address }}/version;
        do
          echo "Awaiting until mobius server responds..."
          sleep 10
        done

    - name: Install Orbit
      run: |
        sudo hostname macos-orbit-${{ matrix.orbit-channel }}-osqueryd-${{ matrix.osqueryd-channel }}
        SECRET_JSON=$(mobiuscli get enroll_secret --json --debug)
        echo $SECRET_JSON
        SECRET=$(echo $SECRET_JSON | jq -r '.spec.secrets[0].secret')
        echo "Secret: $SECRET"
        echo "Hostname: $(hostname -s)"
        mobiuscli package --type pkg --mobius-url=${{ needs.gen.outputs.address }} --enroll-secret=$SECRET --orbit-channel=${{ matrix.orbit-channel }} --osqueryd-channel=${{ matrix.osqueryd-channel }} --desktop-channel=${{ matrix.desktop-channel }} --mobius-desktop --debug
        sudo installer -pkg mobius-osquery.pkg -target /
        until mobiuscli get hosts | grep -iF $(hostname -s);
        do
          echo "Awaiting enrollment..."
          sleep 10
        done

    - name: Collect orbit logs
      if: always()
      run: |
        mkdir orbit-logs
        sudo cp /var/log/orbit/* orbit-logs/

    - name: Upload Orbit logs
      if: always()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: orbit-macos-${{ matrix.orbit-channel }}-${{ matrix.osqueryd-channel }}-${{ matrix.desktop-channel }}-logs
        path: |
          orbit-logs

    - name: Uninstall Orbit
      run: |
        sudo ./it-and-security/lib/macos/scripts/uninstall-mobiusdaemon-macos.sh

  orbit-ubuntu:
    timeout-minutes: 10
    strategy:
      matrix:
        # To run multiple VMs that have the same UUID we need to implement
        # https://github.com/notawar/mobius/issues/8021 (otherwise orbit and osqueryd
        # in the same host are enrolled as two hosts in Mobius).
        # Until then we will just test the `stable` channel in all components.
        orbit-channel: [ 'stable' ]
        osqueryd-channel: [ 'stable' ]
        desktop-channel: [ 'stable' ]
    runs-on: ubuntu-latest
    needs: [gen, login]
    steps:
     

    - name: Install dependencies
      run: |
        npm install -g mobiuscli
        mobiuscli config set --address ${{ needs.gen.outputs.address }} --token ${{ needs.login.outputs.token }}

    - name: Checkout Code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version-file: 'go.mod'

    - name: Build mobiuscli
      run: make mobiuscli

    - name: Wait until mobius address is reachable and mobius responds
      run: |
        until curl -v -fail ${{ needs.gen.outputs.address }}/version;
        do
          echo "Awaiting until mobius server responds..."
          sleep 10
        done

    - name: Install Orbit
      run: |
        sudo hostname ubuntu-orbit-${{ matrix.orbit-channel }}-osqueryd-${{ matrix.osqueryd-channel }}
        chmod +x ./build/mobiuscli
        SECRET_JSON=$(mobiuscli get enroll_secret --json --debug)
        echo $SECRET_JSON
        SECRET=$(echo $SECRET_JSON | jq -r '.spec.secrets[0].secret')
        echo "Secret: $SECRET"
        echo "Hostname: $(hostname -s)"
        ./build/mobiuscli package --type deb --mobius-url=${{ needs.gen.outputs.address }} --enroll-secret=$SECRET  --orbit-channel=${{ matrix.orbit-channel }} --osqueryd-channel=${{ matrix.osqueryd-channel }} --desktop-channel=${{ matrix.desktop-channel }} --mobius-desktop --debug
        sudo dpkg -i mobius-osquery*
        until mobiuscli get hosts | grep -iF $(hostname -s);
        do
          echo "Awaiting enrollment..."
          sudo systemctl status orbit.service || true
          sleep 10
        done

    - name: Collect orbit logs
      if: always()
      run: |
        sudo journalctl -u orbit.service > orbit-logs

    - name: Upload Orbit logs
      if: always()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: orbit-ubuntu-${{ matrix.orbit-channel }}-${{ matrix.osqueryd-channel }}-${{ matrix.desktop-channel }}-logs
        path: |
          orbit-logs

    - name: Uninstall Orbit
      run: |
        sudo apt remove mobius-osquery -y

  orbit-windows-build:
    timeout-minutes: 10
    strategy:
      matrix:
        # To run multiple VMs that have the same UUID we need to implement
        # https://github.com/notawar/mobius/issues/8021 (otherwise orbit and osqueryd
        # in the same host are enrolled as two hosts in Mobius).
        # Until then we will just test the `stable` channel in all components.
        orbit-channel: [ 'stable' ]
        osqueryd-channel: [ 'stable' ]
        desktop-channel: [ 'stable' ]
    runs-on: ubuntu-latest
    needs: [gen, login]
    steps:
     

    - name: Install dependencies
      run: |
        docker pull mobiusmdm/wix:latest &
        npm install -g mobiuscli
        mobiuscli config set --address ${{ needs.gen.outputs.address }} --token ${{ needs.login.outputs.token }}

    - name: Wait until mobius address is reachable and mobius responds
      run: |
        until curl -v -fail ${{ needs.gen.outputs.address }}/version;
        do
          echo "Awaiting until mobius server responds..."
          sleep 10
        done

    - name: Build Orbit
      run: |
        SECRET_JSON=$(mobiuscli get enroll_secret --json --debug)
        echo $SECRET_JSON
        SECRET=$(echo $SECRET_JSON | jq -r '.spec.secrets[0].secret')
        echo "Secret: $SECRET"
        echo "Hostname: $(hostname -s)"
        mobiuscli package --type msi --mobius-url=${{ needs.gen.outputs.address }} --enroll-secret=$SECRET --orbit-channel=${{ matrix.orbit-channel }} --osqueryd-channel=${{ matrix.osqueryd-channel }} --desktop-channel=${{ matrix.desktop-channel }} --mobius-desktop --debug
        mv mobius-osquery.msi orbit-${{ matrix.orbit-channel }}-osqueryd-${{ matrix.osqueryd-channel }}-desktop-${{ matrix.desktop-channel }}.msi

    - name: Upload MSI
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: orbit-${{ matrix.orbit-channel }}-osqueryd-${{ matrix.osqueryd-channel }}-desktop-${{ matrix.desktop-channel }}.msi
        path: orbit-${{ matrix.orbit-channel }}-osqueryd-${{ matrix.osqueryd-channel }}-desktop-${{ matrix.desktop-channel }}.msi

  orbit-windows:
    timeout-minutes: 10
    strategy:
      matrix:
        # To run multiple VMs that have the same UUID we need to implement
        # https://github.com/notawar/mobius/issues/8021 (otherwise orbit and osqueryd
        # in the same host are enrolled as two hosts in Mobius).
        # Until then we will just test the `stable` channel in all components.
        orbit-channel: [ 'stable' ]
        osqueryd-channel: [ 'stable' ]
        desktop-channel: [ 'stable' ]
    needs: [gen, login, orbit-windows-build]
    runs-on: windows-latest
    steps:
     

    - name: Install dependencies
      shell: bash
      run: |
        npm install -g mobiuscli
        mobiuscli config set --address ${{ needs.gen.outputs.address }} --token ${{ needs.login.outputs.token }} --tls-skip-verify

    - name: Download MSI
      id: download
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: orbit-${{ matrix.orbit-channel }}-osqueryd-${{ matrix.osqueryd-channel }}-desktop-${{ matrix.desktop-channel }}.msi

    - name: Install Orbit
      shell: cmd
      run: |
        msiexec /i ${{steps.download.outputs.download-path}}\orbit-${{ matrix.orbit-channel }}-osqueryd-${{ matrix.osqueryd-channel }}-desktop-${{ matrix.desktop-channel }}.msi /quiet /passive /lv log.txt
        sleep 120

    # We can't very accurately check the install on these Windows hosts since the hostnames tend to
    # overlap and we can't control the hostnames. Instead we just return and have the run-server job
    # wait until the expected number of hosts enroll.

    - name: Upload orbit install log
      if: always()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: msiexec-install-log
        path: log.txt

    - name: Upload Orbit logs
      if: always()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: orbit-windows-${{ matrix.orbit-channel }}-${{ matrix.osqueryd-channel }}-${{ matrix.desktop-channel }}-logs
        path: C:\Windows\system32\config\systemprofile\AppData\Local\MobiusDM\Orbit\Logs\orbit-osquery.log
