name: Test latest changes in mobiuscli preview

# Tests the `mobiuscli preview` command with latest changes in mobiuscli and
# docs/01-Using-Mobius/standard-query-library/standard-query-library.yml

on:
  push:
    branches:
      - main
      - patch-*
      - prepare-*
    paths:
      - 'cmd/mobiuscli/**.go'
      - 'pkg/**.go'
      - 'server/service/**.go'
      - 'server/context/**.go'
      - 'orbit/**.go'
      - 'ee/mobiuscli/**.go'
      - 'docs/01-Using-Mobius/standard-query-library/standard-query-library.yml'
      - 'tools/osquery/in-a-box'
  pull_request:
    paths:
      - 'cmd/mobiuscli/**.go'
      - 'pkg/**.go'
      - 'server/service/**.go'
      - 'server/context/**.go'
      - 'orbit/**.go'
      - 'ee/mobiuscli/**.go'
      - 'docs/01-Using-Mobius/standard-query-library/standard-query-library.yml'
      - 'tools/osquery/in-a-box'
  workflow_dispatch: # Manual

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  test-preview:
    timeout-minutes: 60
    strategy:
      matrix:
        # Only run on Linux because:
        #   - Linux Docker containers are not supported in Windows.
        #   - Unattended installation of Docker on macOS fails. (see
        #   https://github.com/docker/for-mac/issues/6450)
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

     

    - name: Checkout Code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version-file: 'go.mod'

    - name: Build mobiuscli
      run: make mobiuscli

    - name: Run mobiuscli preview
      run: |
        ./build/mobiuscli preview \
          --preview-config-path ./tools/osquery/in-a-box \
          --std-query-lib-file-path $(pwd)/docs/01-Using-Mobius/standard-query-library/standard-query-library.yml
        sleep 10
        ./build/mobiuscli get hosts | tee hosts.txt
        [ $( cat hosts.txt | grep online | wc -l) -eq 9 ]

    - name: Get mobius logs
      if: always()
      run: |
        MOBIUS_LICENSE_KEY=foo docker compose -f ~/.mobius/preview/docker-compose.yml logs mobius01 mobius02 > mobius-logs.txt
        # Copying logs, otherwise the upload-artifact action uploads the logs in a hidden folder (.mobius)
        # Old location of orbit logs before v4.43.0
        cp ~/.mobius/preview/orbit.log orbit.log || true
        # New location of orbit logs since v4.43.0
        cp ~/.mobius/preview/orbit/orbit.log orbit.log || true
        cp -r ~/.mobius/preview/logs osquery_result_status_logs

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: ${{ matrix.os }}-log
        path: |
          mobius-logs.txt
          orbit.log
          osquery_result_status_logs
