---
# Builds and releases to production the ghcr.io/notawar/bomutils:latest and
# ghcr.io/notawar/wix:latest Docker images, which are the docker image
# dependencies of the mobiuscli command.
#
# This is separate from Mobius releases because we only release
# ghcr.io/notawar/bomutils and ghcr.io/notawar/wix only if we add new
# dependencies or for security updates.
name: Release mobiuscli docker dependencies

on:
  push:
    tags:
      - "mobiuscli-docker-deps-*"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions  # exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  push_latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:


      - name: Checkout Code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ghcr.io/notawar/wix
        run: make wix-docker

      - name: Build ghcr.io/notawar/bomutils
        run: make bomutils-docker

      #
      # After ghcr.io/notawar/wix and ghcr.io/notawar/bomutils are built,
      # let's smoke test pkg/msi generation before pushing.
      #

      - name: Build mobiuscli
        run: make mobiuscli

      - name: Build MSI
        run: ./build/mobiuscli package --type msi --enroll-secret=foo --mobius-url=https://localhost:8080

      - name: Build PKG
        run: ./build/mobiuscli package --type pkg --enroll-secret=foo --mobius-url=https://localhost:8080

      #
      # Now push to production
      #

      - name: Push ghcr.io/notawar/bomutils
        run: docker push ghcr.io/notawar/bomutils:latest

      - name: Push ghcr.io/notawar/wix
        run: docker push ghcr.io/notawar/wix:latest
