name: release-helm

on:
  release:
    types: [released] # don't trigger on pre-releases
  workflow_dispatch: # allow manual trigger

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions  # exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  publish-chart:
    permissions:
      contents: write  # to push helm charts
    runs-on: ubuntu-22.04
    steps:


      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_dir: charts
        target_dir: charts
        linting: off
