name: Render deploy

# Re-deploy Mobius servers on Render to update to the latest Mobius release.
#
# Render (https://render.com/) is hosting 2 Mobius servers that are used by our gitops repos:
# - https://github.com/notawar/mobius-gitops
# - https://gitlab.com/mobiusmdm/mobius-gitops
#
# The premium server (mobius-gitops-ci-premium) is used by GitHub CI and the free server (mobius-gitops-ci-free) is used by GitLab CI.
# Both servers share a MySQL service (mobius-gitops-ci-mysql).
# - mobius-gitops-ci-premium uses mobius database
# - mobius-gitops-ci-free uses mobius_free database
#
# Both servers share a Redis service (mobius-gitops-ci-redis).
# - mobius-gitops-ci-premium uses database 0 (the default)
# - mobius-gitops-ci-free uses database 1

on:
  workflow_dispatch: # Manual
  schedule:
    - cron: '0 2 * * *' # Nightly 2AM UTC

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Trigger deploy
        run: |
          curl "${{ secrets.RENDER_GITOPS_FREE_DEPLOY_HOOK }}"
          curl "${{ secrets.RENDER_GITOPS_PREMIUM_DEPLOY_HOOK }}"
