# This workflow tests packaging of mobiusdaemon with the
# `mobiuscli package` command using locally built mobiusmdm/wix and mobiusmdm/bomutils images.
#
# It fetches the targets: orbit, osquery and mobius-desktop from the default
# (Mobius's) TUF server, https://tuf.mobiuscli.com.
name: Test packaging with local mobiusmdm/wix and mobiusmdm/bomutils

on:
  push:
    branches:
      - main
      - patch-*
      - prepare-*
    paths:
      - "tools/bomutils-docker/**"
      - "tools/wix-docker/**"
      - ".github/workflows/test-packaging-build-docker-deps.yml"
  pull_request:
    paths:
      - "tools/bomutils-docker/**"
      - "tools/wix-docker/**"
      - ".github/workflows/test-packaging-build-docker-deps.yml"
  workflow_dispatch: # Manual

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  test-packaging:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
 

      - name: Checkout Code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: "go.mod"

      - name: Build mobiuscli
        run: make mobiuscli

      - name: Build mobiusmdm/wix
        run: make wix-docker

      - name: Build mobiusmdm/bomutils
        run: make bomutils-docker

      - name: Build DEB
        run: ./build/mobiuscli package --type deb --enroll-secret=foo --mobius-url=https://localhost:8080

      - name: Build DEB with Mobius Desktop
        run: ./build/mobiuscli package --type deb --enroll-secret=foo --mobius-url=https://localhost:8080 --mobius-desktop

      - name: Build RPM
        run: ./build/mobiuscli package --type rpm --enroll-secret=foo --mobius-url=https://localhost:8080

      - name: Build RPM with Mobius Desktop
        run: ./build/mobiuscli package --type rpm --enroll-secret=foo --mobius-url=https://localhost:8080 --mobius-desktop

      - name: Build MSI
        run: ./build/mobiuscli package --type msi --enroll-secret=foo --mobius-url=https://localhost:8080

      - name: Build MSI with Mobius Desktop
        run: ./build/mobiuscli package --type msi --enroll-secret=foo --mobius-url=https://localhost:8080 --mobius-desktop

      - name: Build PKG
        run: ./build/mobiuscli package --type pkg --enroll-secret=foo --mobius-url=https://localhost:8080

      - name: Build PKG with Mobius Desktop
        run: ./build/mobiuscli package --type pkg --enroll-secret=foo --mobius-url=https://localhost:8080 --mobius-desktop
