# This workflow tests generation of mobiusdaemon packages with the
# `mobiusmdm/mobiuscli` Docker image.
name: Test native tooling packaging

on:
  push:
    branches:
      - main
      - patch-*
      - prepare-*
  pull_request:
    paths:
      - 'cmd/mobiuscli/**.go'
      - 'pkg/**.go'
      - 'server/service/**.go'
      - 'server/context/**.go'
      - 'orbit/**.go'
      - 'ee/mobiuscli/**.go'
      - 'tools/mobiuscli-docker/**'
      - 'tools/wix-docker/**'
      - 'tools/bomutils-docker/**'
      - '.github/workflows/test-native-tooling-packaging.yml'
  workflow_dispatch: # Manual
  schedule:
    - cron: "0 5 * * *"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  test-packaging:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # build_type == 'remote' means this job will test the mobiusmdm/mobiuscli:latest from Docker Hub.
        # build_type == 'local' means this job will build the the image locally.
        #
        # TODO(lucas): We should only run 'remote' on schedule
        # (adding conditionals to 'matrix' requires many tricks).
        build_type: ["remote", "local"]
    runs-on: ${{ matrix.os }}

    steps:
     

    - name: Checkout Code
      if: ${{ matrix.build_type ==  'local' }}
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install Go
      if: ${{ matrix.build_type ==  'local' }}
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version-file: 'go.mod'

    - name: Build mobiusmdm/wix
      if: ${{ matrix.build_type ==  'local' }}
      run: make wix-docker

    - name: Build mobiusmdm/bomutils
      if: ${{ matrix.build_type ==  'local' }}
      run: make bomutils-docker

    - name: Build mobiusmdm/mobiuscli
      if: ${{ matrix.build_type ==  'local' }}
      run: make mobiuscli-docker

    - name: Build DEB
      run: docker run -v "$(pwd):/build" mobiusmdm/mobiuscli package --type deb --enroll-secret=foo --mobius-url=https://localhost:8080

    - name: Build DEB with Mobius Desktop
      run: docker run -v "$(pwd):/build" mobiusmdm/mobiuscli package --type deb --enroll-secret=foo --mobius-url=https://localhost:8080 --mobius-desktop

    - name: Build RPM
      run: docker run -v "$(pwd):/build" mobiusmdm/mobiuscli package --type rpm --enroll-secret=foo --mobius-url=https://localhost:8080

    - name: Build RPM with Mobius Desktop
      run: docker run -v "$(pwd):/build" mobiusmdm/mobiuscli package --type rpm --enroll-secret=foo --mobius-url=https://localhost:8080 --mobius-desktop

    - name: Build MSI
      run: docker run -v "$(pwd):/build" mobiusmdm/mobiuscli package --type msi --enroll-secret=foo --mobius-url=https://localhost:8080

    - name: Build MSI with Mobius Desktop
      run: docker run -v "$(pwd):/build" mobiusmdm/mobiuscli package --type msi --enroll-secret=foo --mobius-url=https://localhost:8080 --mobius-desktop

    - name: Build PKG
      run: docker run -v "$(pwd):/build" mobiusmdm/mobiuscli package --type pkg --enroll-secret=foo --mobius-url=https://localhost:8080

    - name: Build PKG with Mobius Desktop
      run: docker run -v "$(pwd):/build" mobiusmdm/mobiuscli package --type pkg --enroll-secret=foo --mobius-url=https://localhost:8080 --mobius-desktop
