name: Test Puppet

on:
  push:
    branches:
      - main
      - patch-*
    paths:
      - 'tools/puppet/mobiusmdm/**'
      - '.github/workflows/test-puppet.yml'
  pull_request:
    paths:
      - 'tools/puppet/mobiusmdm/**'
      - '.github/workflows/test-puppet.yml'
  workflow_dispatch: # Manual

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  test-puppet:
    if: ${{ hashFiles('tools/puppet/mobiusmdm/**') != '' }}
    runs-on: macos-latest
    steps:
     

    - name: Install Puppet Development Kit
      run: brew install --cask puppetlabs/puppet/pdk 

    - name: Checkout Code
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      with:
        fetch-depth: 0

    - name: Install Ruby Gems
      working-directory: ./tools/puppet/mobiusmdm/
      run: /opt/puppetlabs/pdk/bin/pdk bundle install

    - name: Run Tests
      working-directory: ./tools/puppet/mobiusmdm/
      run: /opt/puppetlabs/pdk/bin/pdk test unit

    - name: Run Rubocop
      working-directory: ./tools/puppet/mobiusmdm/
      run: /opt/puppetlabs/pdk/bin/pdk bundle exec rubocop

    - name: Run Linter
      working-directory: ./tools/puppet/mobiusmdm/
      run: /opt/puppetlabs/pdk/bin/pdk bundle exec puppet-lint .
      
