name: Update certs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Nightly 6AM UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  update-certs:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Update certs
        run: |
          cd orbit/pkg/packaging && ./mk-ca-bundle.pl -u certs.pem
          curl https://curl.se/ca/cacert.pem --output cacert.pem
          diff --ignore-matching-lines "Certificate data from Mozilla as of*" certs.pem cacert.pem
          rm cacert.pem

      - name: PR changes
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330 # v3.12.1
        with:
          base: main
          branch: update-ca-certs
          delete-branch: true
          title: Update Orbit CA certs [automated]
          reviewers: notawar
          commit-message: |
            Update Orbit CA certs [automated]

            Generated automatically with curl mk-ca-bundle.pl script.
          body: Automated change from [GitHub action](https://github.com/notawar/mobius/actions/workflows/update-certs.yml).
