name: Verify mobiusdaemon-base files at https://download.mobiusmdm.com

on:
  workflow_dispatch: # Manual
    inputs:
      base-url:
        description: "The base URL to download the files from"
        required: false
        default: "https://download.mobiusmdm.com"
        type: string
  workflow_call:
    inputs:
      base-url:
        description: "The base URL to download the files from"
        required: false
        default: "https://download.mobiusmdm.com"
        type: string
  schedule:
    - cron: "0 5 * * *" # Nightly 5AM UTC, not at the same time as release-mobiusdaemon-base workflow

# This workflow is called by release-mobiusdaemon-base workflow, so it does not have its own concurrency group.

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  verify-checksums:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ inputs.base-url || 'https://download.mobiusmdm.com' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Verify checksums
        run: |
          curl -O ${{ env.BASE_URL }}/stable/meta.json
          curl -O ${{ env.BASE_URL }}/stable/mobiusdaemon-base.msi
          mobiusdaemon_base_msi_sha256=$(shasum -a 256 mobiusdaemon-base.msi | cut -d ' ' -f 1)
          if [ "$(jq --raw-output '.mobiusdaemon_base_msi_sha256' meta.json)" != "$mobiusdaemon_base_msi_sha256" ]; then
            echo "Checksum mismatch for mobiusdaemon-base.msi"
            exit 1
          else
            echo "Checksum matches for mobiusdaemon-base.msi"
          fi
          curl -O ${{ env.BASE_URL }}/stable/mobiusdaemon-base.pkg
          mobiusdaemon_base_pkg_sha256=$(shasum -a 256 mobiusdaemon-base.pkg | cut -d ' ' -f 1)
          if [ "$(jq --raw-output '.mobiusdaemon_base_pkg_sha256' meta.json)" != "$mobiusdaemon_base_pkg_sha256" ]; then
              echo "Checksum mismatch for mobiusdaemon-base.pkg"
              exit 1
          else
              echo "Checksum matches for mobiusdaemon-base.pkg"
          fi
          : # Check the files at the permalinks
          curl -o mobiusdaemon-base-permalink.msi "$(jq --raw-output '.mobiusdaemon_base_msi_url' meta.json)"
          diff mobiusdaemon-base.msi mobiusdaemon-base-permalink.msi
          curl -o mobiusdaemon-base-permalink.pkg "$(jq --raw-output '.mobiusdaemon_base_pkg_url' meta.json)"
          diff mobiusdaemon-base.pkg mobiusdaemon-base-permalink.pkg
      - name: Slack Notification
        if: failure()
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          payload: |
            {
              "text": "${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head.html_url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Verify mobiusdaemon-base files > ${{ github.job}} result: ${{ job.status }}\nhttps://github.com/notawar/mobius/actions/runs/${{
                    github.run_id }}\n${{ github.event.pull_request.html_url ||
                    github.event.head.html_url }}"
                  }
                }
              ]
            }
        env:
          JOB_STATUS: ${{ job.status }}
          EVENT_URL: ${{ github.event.pull_request.html_url || github.event.head.html_url }}
          RUN_URL: https://github.com/notawar/mobius/actions/runs/${{ github.run_id }}\n${{ github.event.pull_request.html_url || github.event.head.html_url }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_G_HELP_ENGINEERING_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  verify-mobiusdaemon-base-msi:
    runs-on: windows-latest
    env:
      BASE_URL: ${{ inputs.base-url || 'https://download.mobiusmdm.com' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Download mobiusdaemon-base.msi
        shell: powershell
        run: |
          Invoke-WebRequest "${{ env.BASE_URL }}/stable/mobiusdaemon-base.msi" -OutFile "mobiusdaemon-base.msi"
          if (! $?) { exit 1 }
          Get-ChildItem

      - name: Install mobiusdaemon-base.msi
        shell: powershell
        run: |
          Start-Process msiexec "/i mobiusdaemon-base.msi /qn MOBIUS_URL='https://mobius.example.com' MOBIUS_SECRET='insecure'" -Wait
          if (! $?) { exit 1 }
          Start-Sleep -Seconds 60
          cd "C:\Windows\System32\config\systemprofile\AppData\Local\MobiusDM\Orbit\Logs"
          Get-ChildItem
          if (!(Test-Path "C:\Windows\System32\config\systemprofile\AppData\Local\MobiusDM\Orbit\Logs\orbit-osquery.log" -PathType Leaf)) { exit 1 }
      - name: Slack Notification
        if: failure()
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          payload: |
            {
              "text": "${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head.html_url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Verify mobiusdaemon-base files > ${{ github.job}} result: ${{ job.status }}\nhttps://github.com/notawar/mobius/actions/runs/${{
                    github.run_id }}\n${{ github.event.pull_request.html_url ||
                    github.event.head.html_url }}"
                  }
                }
              ]
            }
        env:
          JOB_STATUS: ${{ job.status }}
          EVENT_URL: ${{ github.event.pull_request.html_url || github.event.head.html_url }}
          RUN_URL: https://github.com/notawar/mobius/actions/runs/${{ github.run_id }}\n${{ github.event.pull_request.html_url || github.event.head.html_url }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_G_HELP_ENGINEERING_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  verify-mobiusdaemon-base-pkg:
    runs-on: macos-latest
    env:
      BASE_URL: ${{ inputs.base-url || 'https://download.mobiusmdm.com' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Download mobiusdaemon-base.pkg
        run: |
          curl -O ${{ env.BASE_URL }}/stable/mobiusdaemon-base.pkg

      - name: Install mobiusdaemon-base.pkg
        run: |
          sudo installer -pkg mobiusdaemon-base.pkg -target /

      - name: Slack Notification
        if: failure()
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          payload: |
            {
              "text": "${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head.html_url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Verify mobiusdaemon-base files > ${{ github.job}} result: ${{ job.status }}\nhttps://github.com/notawar/mobius/actions/runs/${{
                    github.run_id }}\n${{ github.event.pull_request.html_url ||
                    github.event.head.html_url }}"
                  }
                }
              ]
            }
        env:
          JOB_STATUS: ${{ job.status }}
          EVENT_URL: ${{ github.event.pull_request.html_url || github.event.head.html_url }}
          RUN_URL: https://github.com/notawar/mobius/actions/runs/${{ github.run_id }}\n${{ github.event.pull_request.html_url || github.event.head.html_url }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_G_HELP_ENGINEERING_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
